// ═══════════════════════════════════════════════════
// Neurno — Generated by Pyix Bot Builder
// ═══════════════════════════════════════════════════
const { Client, GatewayIntentBits, EmbedBuilder, PermissionFlagsBits, PermissionsBitField, ChannelType } = require('discord.js');


const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
    GatewayIntentBits.GuildMembers,
    GatewayIntentBits.GuildModeration,
    GatewayIntentBits.GuildPresences,
    GatewayIntentBits.GuildMessageReactions
  ]
});

const PREFIX = '!';
const warnings = new Map();

const cooldowns = new Map();

client.once('ready', async (readyClient) => {
  console.log(`✅ ${client.user.tag} is online!`);
  client.user.setPresence({
    status: 'online',
    activities: [{ name: 'JUBU IS A MINION', type: 0 }]
  });
});

client.on('messageCreate', async (message) => {
  if (message.author.bot) return;

  if (!message.content.startsWith(PREFIX)) return;
  const args = message.content.slice(PREFIX.length).trim().split(/ +/);
  let commandName = args.shift().toLowerCase();

  // Cooldown check
  const cdKey = `${commandName}-${message.author.id}`;
  if (cooldowns.has(cdKey)) {
    const remaining = ((cooldowns.get(cdKey) - Date.now()) / 1000).toFixed(1);
    if (remaining > 0) return message.reply(`⏳ Please wait ${remaining}s before using this command again.`);
  }

  if (commandName === 'kick') {
    if (!message.member.permissions.has(PermissionFlagsBits.KickMembers)) return message.reply(`❌ You do not have permission to kick members.`);
    try { await message.delete(); } catch(e) {}
    cooldowns.set(cdKey, Date.now() + 3000);
    setTimeout(() => cooldowns.delete(cdKey), 3000);
    const target = message.mentions.members.first();
    if (!target) return message.channel.send(`❌ Please mention a user to kick.`);
    if (!target.kickable) return message.channel.send(`❌ I cannot kick this user. They may have a higher role.`);
    const reason = args.slice(1).join(' ') || 'No reason provided';
    try { await target.send(`You have been kicked from **{server}** by **{author}**.
Reason: {reason}`.replace(/{server}/g, message.guild.name).replace(/{author}/g, message.author.tag).replace(/{reason}/g, reason)); } catch(e) {}
    await target.kick(reason);
    const reply = `✅ **{target}** has been kicked by **{author}**!
Reason: {reason}`.replace(/{target}/g, target.user.tag).replace(/{author}/g, message.author.tag).replace(/{reason}/g, reason);
    const embed = new EmbedBuilder().setDescription(reply).setColor('#ff7814').setTimestamp();
    message.channel.send({ embeds: [embed] });
    
  }
});

client.login('');

// Graceful shutdown — watches for stop signal file
const __fs = require('fs');
const __path = require('path');
const __stopFile = __path.join(__dirname, '_pyix_stop');
setInterval(() => {
  if (__fs.existsSync(__stopFile)) {
    try { __fs.unlinkSync(__stopFile); } catch(e) {}
    console.log('🛑 Shutting down...');
    client.destroy();
    setTimeout(() => process.exit(0), 500);
  }
}, 300);
